#+TITLE: Doom config
#+AUTHOR: Sebastian Callh
#+EMAIL: sebastian.callh@gmail.com
#+PROPERTY: header-args:elisp :tangle yes :exports code

* Personal Doom Configuration
This config file is intended to be used with [[https://github.com/hlissner/doom-emacs][Doom emacs]]. Since Doom is very batteries-included, this file mostly contains personal touches.
Using the [[file:init.el::literate][literate module]] this file is tangled on save and used instead of a ~config.el~ file.

* Personal
#+begin_src elisp
(setq auth-sources '("~/.authinfo"))
(setq user-full-name "Sebastian Callh"
      user-mail-address "sebastian.callh@gmail.com")
#+end_src

* Localisation
#+begin_src elisp
(use-package! flyspell
  :init (setq ispell-dictionary "en_GB"))
(setq system-time-locale "C")
#+end_src

* Custom keybinds
#+begin_src elisp
(defun kill-current-buffer ()
  (interactive)
  (kill-buffer (current-buffer)))

(global-set-key (kbd "C-w") 'backward-kill-word)
(global-set-key (kbd "C-x k") 'kill-current-buffer)
(global-set-key (kbd "C-x C-k") 'kill-region)
(global-set-key (kbd "M-o") 'other-window)
(global-set-key (kbd "M-;") 'comment-dwim)
#+end_src

* Aesthetics
** Dashboard
#+begin_src elisp
(setq fancy-splash-image "~/.doom.d/images/lambda250.png")
#+end_src

** Theme
#+begin_src elisp
(setq doom-theme 'doom-zenburn)
#+end_src

** Font
Use ~mixed-pitch~ to have separate fonts in code blocks and in prose. The Vollkorn typeface is available at [[http://vollkorn-typeface.com/][their website]].

#+begin_src elisp
(use-package! mixed-pitch
  :hook
  (text-mode . mixed-pitch-mode))

(setq doom-font (font-spec :family "Fira Code" :size 22)
      doom-variable-pitch-font (font-spec :family "Vollkorn")
      doom-unicode-font (font-spec :family "Fira Code")
      doom-big-font (font-spec :family "Fira Code" :size 28))
#+end_src


* Performance
  Also disable some packages in [[file:packages.el::;: Pemoved for performance reason][packages.el]].
#+begin_src elisp
(setq display-line-numbers-type 'nil)
#+end_src

* Org
#+begin_src elisp
(use-package! org
  :init (setq org-directory "~/Dropbox/org")
  :config
  (setq org-startup-folded t)
  (setq org-hide-emphasis-markers t)
  (setq org-ellipsis '"…")
  (setq org-superstar-headline-bullets-list '("❍"))

  (custom-set-faces
   '(org-level-1 ((t (:inherit outline-1 :height 1.2))))
   '(org-level-2 ((t (:inherit outline-2 :height 1.15))))
   '(org-level-3 ((t (:inherit outline-3 :height 1.1))))
   '(org-level-4 ((t (:inherit outline-4 :height 1.0))))
   '(org-level-5 ((t (:inherit outline-5 :height 1.0))))))
#+end_src

* Packages
** Avy
#+begin_src elisp
(use-package! avy
  :config
  (setq avy-all-windows t)
  (global-set-key (kbd "C-:") 'avy-goto-char))
#+end_src

** Tramp
#+begin_src elisp
(after! tramp
  :config
  (setq recentf-auto-cleanup 'never)
  (setq tramp-verbose 3))
#+end_src

** Projectile
Solves the [[https://github.com/bbatsov/projectile/issues/657][issue]] where ~Projectile~ lags over ~Tramp~.
#+begin_src elisp
(use-package! projectile
  :config
  (setq projectile-mode-line "Projectile"))
#+end_src

**  Company-posframe
[[*Font][Mixed pitch]] allows different fonts in org mode for prose and code, however, this doesn't interact super great with company. [[https://github.com/tumashu/company-posframe/][Company-posframe]] solves this. [[https://github.com/sebastiencs/company-box][Company-box]] looks quite a bit nicer with icons and docstring-popup, but it crashes when used in ~emacs-jupyter~, which is super sad. Added in [[file:packages.el::package! company-posframe][package.el]].

#+begin_src elisp
(use-package! company-posframe
  :hook (company-mode . company-posframe-mode))
#+end_src

* Programming
** Data science
*** Ess
Unfortunately [[https://github.com/gjkerns/ob-julia/blob/master/ob-julia-doc.org][needed]] for ~ob-julia~.
#+begin_src elisp
(after! ess
  (setq inferior-julia-program "/usr/local/bin/julia"))
#+end_src

*** Julia
Config can be in the Julia module [[https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/julia/README.org][README]]. ~julia-lsp~ installed in [[file:packages.el::package! lsp-julia :recipe (:host github :repo "non-jedi/lsp-julia")][package.el]].
#+begin_src elisp
(setq lsp-julia-default-environment "~/.julia/environments/v1.5")
#+end_src
